### ISSUE TITLE
Cannot read properties of null (reading 'removeAttribute')

### ISSUE THREAD

**Issue by JunioCalu** [ffplayout/ffplayout#785]
### Describe the bug

On mobile screens, the following error is presented when switching between the media and home pages (resource monitor): 

```shell
Uncaught TypeError: Cannot read properties of null (reading 'removeAttribute')
    at ClcT72Bh.js:1:1601
``` 

```typescript
{
            name: r("button.configure"),
            link: t({
                name: "configure"
            })
        }]);
        c.value === "dark" && (p.darkMode = !0);
        function P() {
            setTimeout( () => {
                _.value = !1,
                x.value.removeAttribute("open"),
                console.log("close")
            }
            , 200)
        }
``` 

### To Reproduce

1. Go to the media page and then return to the home page (resource monitor):

### Desktop/Server/Software (please complete the following information):

- OS: ubuntu 22.04
- ffplayout 0.24.0-beta5
- ffmpeg 7.0.1
- are you using the current master of ffplayout? Yes

### Logging:

```shell
Uncaught TypeError: Cannot read properties of null (reading 'removeAttribute')
    at ClcT72Bh.js:1:1601
(anonymous) @ ClcT72Bh.js:1
setTimeout
P @ ClcT72Bh.js:1
l.onClick.u.<computed>.u.<computed> @ ClcT72Bh.js:1
(anonymous) @ kRRW2e9l.js:19
ec @ kRRW2e9l.js:14
Ia @ kRRW2e9l.js:14
Ia @ kRRW2e9l.js:14
n @ kRRW2e9l.js:19
```

**Comment by jb-alvarado** [comment]
All your reports should be fixed now, thanks.

**Comment by JunioCalu** [comment]
Thank you for your corrections, it seems we are very close to the release now.
