### ISSUE TITLE
Issues Identified in Version 0.24.0-rc2: Configuration Saving, User Management, Playback, etc.

### ISSUE THREAD

**Issue by JunioCalu** [ffplayout/ffplayout#803]
### Describe the bug

I have compiled a list of possible new issues found in version 0.24.0-rc2 below. This list is open for analysis; I've pointed out some details that may not be potential bugs but could simply be descriptions of normal system behavior.

### To Reproduce

1. On the "configure/playout" page, the email configuration field "mail_level" does not accept the value "WARNING". No other field on the "configure/playout" page can be saved after attempting to save a value greater than 199 in the "interval" field of the email configuration.

2. On the "configure/playout" page, the fields "ffmpeg_level" and "ingest_level" are accepting values other than DEBUG, INFO, WARNING, and ERROR.

3. Administrative users created through the "Configure/User" page cannot manage or administer other users' profile data, cannot add new administrative or non-administrative users, and do not have access to the "Configure/Advanced" page.

4. The message "update profile success" is displayed even when a user's profile is updated and the "New password" and "Confirm password" fields are different, or when one of the fields is empty, or when both fields are empty.

5. The message "update profile success" is displayed even when a user's profile is updated and the "Email," "New password," and "Confirm password" fields are empty.

6. On the "Configure/Playout" page, the "audio_channels" field does not save a number greater than 255 channels; saving a value higher than 255 causes an error message, and after this error, no other field on the "Configure/Playout" page can be saved.

7. When a large number of channels are added, such as 37 channels, the channel selection menu cannot display the complete list of channels; part of the channel list is "cut off" from the web browser's viewport.

8. The settings on the "Configure/Advanced" page are saved equally for all channels.

9. The "--shared" parameter only shares the "00-assets" directory by default, and the "filler" directory is not being shared by default.

10. There is a possible error related to the new VTT subtitles preview feature: when a non-administrative user is added, both the player page and the media page do not load/display the media files, and an error related to the VTT subtitles preview is displayed in the web console. Note: I couldn't reproduce this error after it appeared the first time.

11. 

    ```
    Uncaught (in promise) SyntaxError: Unexpected end of JSON input
        at zUJrEyj0.js:1:18269

    async function y() {
        fetch("/api/users", {
            method: "GET",
            headers: l.authHeader
        }).then(m => m.json()).then(m => {
            s.value = m,
            h.value = d.currentUser
        })
    }
    ```

12. The player page does not display/update the next day's playlist on the screen when the previous day's playlist is finished. The problem seems to be time-related; I found that at night, when the previous day's playlist ends, the next day's playlist is not updated on the screen. However, in the afternoon of that same next day, it updates when the playout is started manually. I did not test it in the morning.

13. In version 0.24.0, there was an average increase of 20% to 70% in CPU usage compared to version 0.23.2, which on average consumed 90% to 100% CPU in a usage scenario without a graphics card.

14. When the playlist completes the 24-hour cycle, the player is not stopped; playback continues, but no currently playing track is highlighted in green.

15. If the video of the last track in the playlist has a total duration of 28 seconds, it is skipped and not played.

16. On the "configure/playout" page, the active state of the "add_logo" checkbox is not saved after reloading the configuration page.

### Desktop/Server/Software (please complete the following information):

- OS: ubuntu 22.04
- ffplayout 0.24.0-rc2
- ffmpeg 7.0.1
- are you using the current master of ffplayout? Yes

**Comment by jb-alvarado** [comment]
- 1., 2., 4. -7., 16. should now be obsolete.
- 3. Only a global admin can create channel admins and users. A channel admin cannot create users or other admins. A global user can only be added via CLI.
- 9. maybe I will not expose the `--shared` command in the final version, it is mostly made for usage inside containers, where one root folder with different sub folders per channel are mandatory. A global admin can always set channel storage to any location.
- 12., 14. there is some hiccups in the frontend when a day is finish, but currently I tread it with low priority because at this time most people should sleep :-). If someone have more motivation, he is welcome to work on that and create a pull request.  
- 13. I cannot confirm this:
v0.23:
```BASH
# ps -e -o pid,size,%cpu:7,%mem,cmd --sort=-%cpu | grep -v grep | grep -E "%CPU %MEM|ffplayout|ffpapi"
PID  SIZE    %CPU %MEM CMD
778 33376     0.9  0.0 /usr/bin/ffplayout
777 49960     0.1  0.1 /usr/bin/ffpapi -l 0.0.0.0:8787
```
v0.24:
```BASH
# ps -e -o pid,size:6,%cpu,%mem,cmd --sort=-%cpu | grep -v grep | grep -E "SIZE %CPU %MEM|ffplayout|ffpapi"
PID   SIZE %CPU %MEM CMD
677  52668  0.1  0.1 /usr/bin/ffplayout -l 0.0.0.0:8787
```

**Comment by JunioCalu** [comment]
> * 13 - I cannot confirm this:
>   v0.23:
> 
> ```shell
> # ps -e -o pid,size,%cpu:7,%mem,cmd --sort=-%cpu | grep -v grep | grep -E "%CPU %MEM|ffplayout|ffpapi"
> PID  SIZE    %CPU %MEM CMD
> 778 33376     0.9  0.0 /usr/bin/ffplayout
> 777 49960     0.1  0.1 /usr/bin/ffpapi -l 0.0.0.0:8787
> ```
> 
> v0.24:
> 
> ```shell
> # ps -e -o pid,size:6,%cpu,%mem,cmd --sort=-%cpu | grep -v grep | grep -E "SIZE %CPU %MEM|ffplayout|ffpapi"
> PID   SIZE %CPU %MEM CMD
> 677  52668  0.1  0.1 /usr/bin/ffplayout -l 0.0.0.0:8787
> ```

In note 13, I was referring to the ffmpeg process launched by ffplayout. In my case, this increase occurred, but to confirm with more certainty, I would need to test on more types of processors.

**Comment by jb-alvarado** [comment]
Every channel has its one advanced settings, they where not loaded correctly.

**Comment by JunioCalu** [comment]
Update ffplayout 0.24.0-rc3:

17. New users created from the "configure/user" page are unable to modify settings on the "configure/channel" page. Steps to reproduce:
 a. Create a new administrative or non-administrative user.
 b. Log out of the current account.
 c. Log in to the new account.
 d. Attempt to modify the settings on "configure/channel."
 e. Error log displayed in the console: "PATCH http://127.0.0.1:8788/api/channel/1 403 (Forbidden)"

18. "Uncaught (in promise) SyntaxError: Unexpected." Steps to reproduce:
 a. Log in with any user account.
 b. Navigate to the "configure/user" page.
 c. Check the web console for the following error message: "Uncaught (in promise) SyntaxError: Unexpected."

19. "GET http://127.0.0.1:8788/api/playout/advanced/1 403 (Forbidden)"

     a. Create a non-administrative user.
     b. Log out of the current account.
     c. Log in to the new non-administrative account.
     d. Attempt to modify the settings on "configure/channel."
     e. Observe the error logs displayed in the web console:
        - "PATCH http://127.0.0.1:8788/api/channel/1 403 (Forbidden)"
        - "GET http://127.0.0.1:8788/api/playout/advanced/1 403 (Forbidden)"

**Comment by JunioCalu** [comment]
> Observation:
> 
> In 18, the steps to reproduce are:
> 
> a. Log in to a non-global administrative account or a non-administrative account. b. Navigate to the "configure/user" page. c. The log displayed in the web console is:
> 
> `GET http://127.0.0.1:8788/api/users 403 (Forbidden)` `Uncaught (in promise) SyntaxError: Unexpected end of JSON input`

**Comment by JunioCalu** [comment]
20. On the player page, the pixel width required to display the media selection panel still seems a bit too high. The image below is from a notebook screen, and the media panel is not being displayed when windows are placed side by side. I believe the media selection panel should start being displayed at a minimum viewport resolution of 640 x 360 px.

![image](https://github.com/user-attachments/assets/b55a93fe-a576-40a9-a471-f63ecd702f25)

**Comment by JunioCalu** [comment]
21. On the "Configure/Channel" page, the "extra extensions" field is editable, but the text font is being displayed with a color palette typically used for non-editable fields.

![image](https://github.com/user-attachments/assets/e4e31cc9-5d85-4483-bbb3-56d3884a5415)

**Comment by jb-alvarado** [comment]
Thanks for testing! I think we are almost ready for a final release. Maybe on this Sunday, or next week.

**Comment by JunioCalu** [comment]
> Thanks for testing! I think we are almost ready for a final release. Maybe on this Sunday, or next week.

Thank you, and congratulations on your work on this version. The codebase is becoming increasingly complex and extensive, so while we don't yet have a full understanding of it, you're the only one who can really give us a hand.

**Comment by JunioCalu** [comment]
I hope these are the final details for the current master version:

21. I think the volume output of ffplayout's embedded player is too high. Even when the player volume is reduced to 2%, the audio remains quite audible. It might be better to reduce the output volume by 97% or 98%.

22. The player is not scrolling the playlist to the correct track when the "Start playout service" button is first clicked. A page refresh is needed for the player to scroll to the correct position. Steps to reproduce:
    a. Open ffplayout in an incognito browser window.
    b. Create a full playlist.
    c. Click "Start playout service."
    d. The playlist does not scroll to the correct track.

**Comment by JunioCalu** [comment]
23. The "filler" folder is not being shared across all channel media storage directories, such as /1, /2, /3, etc. I believe this could be resolved by creating symbolic links (using the command `ln -s`) from the "filler" folder to the other media storage directories, but the frontend doesn’t seem able to display symbolic links for folders, based on my testing. If this behavior is expected by design, please disregard this issue.

**Comment by jb-alvarado** [comment]
There is two ways of using the storage:

1. Use one storage root for all channels. When you create a new channel, remove the added number.

2. Use for every channel its own storage root. Then there is no share of assets, fonts, fillers etc. If you use this, only some assets gets copied, on channel creating.

**Comment by JunioCalu** [comment]
24. C1OipWCw.js:14 TypeError: Cannot read properties of undefined (reading 'add_text')
    at Proxy.<anonymous> (B4I1Ljex.js:1:6521)
    at yc (C1OipWCw.js:15:29540)
    at Tv.C [as fn] (C1OipWCw.js:15:21240)
    at Tv.run (C1OipWCw.js:10:1741)
    at Tv.runIfDirty (C1OipWCw.js:10:2051)
    at Ii (C1OipWCw.js:14:46)
    at Vv (C1OipWCw.js:14:1799)
    
      steps:
      
      a. create 2 channels
      
      b. kill the playout process
      
      c. start a new process:
      
      d. `sudo ./target/x86_64-unknown-linux-musl/release/ffplayout --public=./frontend/.output/public --db=./db --logs=./log -l 0.0.0.0:8788`
      
      e. access the frontend in an incognito window, and navigate to the player page
      
      f. check the error log in the web console.

**Comment by JunioCalu** [comment]
25. ffplayout 0.24.0 (master):  Some warnings appear during the frontend build process. Is there any way to fix this? I'm using Node v18.20.4:

    a.
    ```shell
    npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
    npm warn deprecated npmlog@5.0.1: This package is no longer supported.
    npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
    npm warn deprecated are-we-there-yet@2.0.0: This package is no longer supported.
    npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
    npm warn deprecated gauge@3.0.2: This package is no longer supported.
    
    ``` 
    
    b.
    
    ```shell
    transforming (39) node_modules/nuxt/dist/app/composables/router.js=============
    
    WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.
    
    You may find that it works just fine, or you may not.
    
    SUPPORTED TYPESCRIPT VERSIONS: >=4.7.4 <5.6.0
    
    YOUR TYPESCRIPT VERSION: 5.6.3
    
    Please only submit bug reports when using the officially supported version.
    
    ``` 
    
    c.
    ```shell
    [plugin unplugin-vue-i18n:directive] Sourcemap is likely to be incorrect: a plugin (unplugin-vue-i18n:directive) was used to transform files, but didn't generate a sourcemap for the transformation. Consult the plugin documentation for help
    ```

**Comment by jb-alvarado** [comment]
You can ignore them.

**Comment by JunioCalu** [comment]
26. Relative file paths do not work with `tee` when the parameter order is altered:

This works:

```shell
-c:v libx264 -crf 23 -x264-params keyint=50:min-keyint=25:scenecut=-1 -maxrate 1300k -bufsize 2600k -preset faster -tune zerolatency -profile:v Main -level 3.1 -c:a aac -ar 44100 -b:a 128k -flags +cgop -muxpreload 0 -muxdelay 0 -f tee 
"[f=flv:onfail=ignore]rtmp://127.0.0.1:1935/798e3a9e-47b5-4cd5-8079-76a20e03fee6.stream| 
[f=mpegts:onfail=ignore]udp://127.0.0.1:1234?pkt_size=1316| 
[f=hls:hls_time=6:hls_list_size=600:hls_flags=append_list+delete_segments+omit_endlist:hls_segment_filename=live/stream-%d.ts]live/stream.m3u8"
``` 

This does not work:
```shell
-c:v libx264 -crf 23 -x264-params keyint=50:min-keyint=25:scenecut=-1 -maxrate 1300k -bufsize 2600k -preset faster -tune zerolatency -profile:v Main -level 3.1 -c:a aac -ar 44100 -b:a 128k -flags +cgop -muxpreload 0 -muxdelay 0 -f tee "
[f=hls:hls_time=6:hls_list_size=600:hls_flags=append_list+delete_segments+omit_endlist:hls_segment_filename=live/stream-%d.ts]live/stream.m3u8|
[f=flv:onfail=ignore]rtmp://127.0.0.1:1935/798e3a9e-47b5-4cd5-8079-76a20e03fee6.stream| 
[f=mpegts:onfail=ignore]udp://127.0.0.1:1234?pkt_size=1316"
``` 

This works:

```shell
-c:v libx264 -crf 23 -x264-params keyint=50:min-keyint=25:scenecut=-1 -maxrate 1300k -bufsize 2600k -preset faster -tune zerolatency -profile:v Main -level 3.1 -c:a aac -ar 44100 -b:a 128k -flags +cgop -muxpreload 0 -muxdelay 0 -f tee "[f=flv:onfail=ignore]rtmp://127.0.0.1:1935/798e3a9e-47b5-4cd5-8079-76a20e03fee6.stream|
[f=hls:hls_time=6:hls_list_size=600:hls_flags=append_list+delete_segments+omit_endlist:hls_segment_filename=live/stream-%d.ts]live/stream.m3u8"
``` 

This does not work:

```shell
-c:v libx264 -crf 23 -x264-params keyint=50:min-keyint=25:scenecut=-1 -maxrate 1300k -bufsize 2600k -preset faster -tune zerolatency -profile:v Main -level 3.1 -c:a aac -ar 44100 -b:a 128k -flags +cgop -muxpreload 0 -muxdelay 0 -f tee "
[f=hls:hls_time=6:hls_list_size=600:hls_flags=append_list+delete_segments+omit_endlist:hls_segment_filename=live/stream-%d.ts]live/stream.m3u8|
[f=flv:onfail=ignore]rtmp://127.0.0.1:1935/798e3a9e-47b5-4cd5-8079-76a20e03fee6.stream"
```

**Comment by JunioCalu** [comment]
27. The mobile menu is not hidden when the browser viewport is resized on desktop screens.

![image](https://github.com/user-attachments/assets/efaa6a0c-2691-4c62-9afb-46e236c724b3)


![image](https://github.com/user-attachments/assets/52e29925-d8ee-4482-9392-6c4fc8ba4f5e)

**Comment by JunioCalu** [comment]
28. The directory path configuration "/var/lib/ffplayout/tv-media/1/filler/filler.mp4" for the filler file of the first channel is being applied to all newly created channels. It might be better to set the filler path to "/var/lib/ffplayout/tv-media/filler" and create a symbolic link from this folder to tv-media/1/, tv-media/2/, tv-media/3/, and so on. Additionally, consider configuring ffplayout to allow the creation of an exclusive filler folder for each new channel, in case a channel administrator wants to create a filler folder within their channel's storage directory.

**Comment by jb-alvarado** [comment]
Sorry, but I don't understand this thing about the filler. `filler/filler.mp4` ist just a placeholder, by default there is no folder filler, and no file filler.mp4 in it. For every channel you can set your own fillers, just add an existing path. If you want the same storage and filler for all channel, set the same storage location for all channels, in the channel tab.

**Comment by JunioCalu** [comment]
> Sorry, but I don't understand this thing about the filler. `filler/filler.mp4` ist just a placeholder, by default there is no folder filler, and no file filler.mp4 in it. For every channel you can set your own fillers, just add an existing path. If you want the same storage and filler for all channel, set the same storage location for all channels, in the channel tab.

I identified a system behavior where the filler.mp4 from channel 1 was also being used by channel 2, and probably by other channels, according to the default configuration. However, checking again now, I can't reproduce the issue, so I'll remove the note until I can confirm it more definitively.

**Comment by jb-alvarado** [comment]
But did you copy a file with name filler.mp4 to the storage?

**Comment by JunioCalu** [comment]
No, channel 1 contained the file, and channel 2 did not. The only configuration change was setting the storage path of channel 1 from .../tv-media/ to .../tv-media/1.
